version: "{branch}.{build}"
image:
  - "Visual Studio 2015"
environment:
  PATH: "C:\\msys64\\usr\\bin;%PATH%"
  matrix:
    - APPVEYOR_BITS: 32
    - APPVEYOR_BITS: 64
cache:
  - '%LOCALAPPDATA%\pip\Cache'
init:
  - git config --global core.autocrlf true
install:
  - bash -e install.sh
build:
  verbosity: detailed
build_script:
  - bash -e build.sh
test: off
matrix:
  fast_finish: true
artifacts:
  - path: build\dist\smi2ass.*
    name: Releases
deploy:
  provider: GitHub
  auth_token:
    secure: "NFYPLE7fXMSzXHZGA9EEXaGwvgct/x4tnWYIPsvKOK0FmNvYeUT6wxf/pwy/NMc5"
  artifact: /smi2ass\..*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
